---
# VM Templates Role - Default Variables

# Cloud image URLs - using stable URLs that redirect to latest
vm_image_urls:
  debian12: "https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.qcow2"
  debian11: "https://cloud.debian.org/images/cloud/bullseye/latest/debian-11-generic-amd64.qcow2"
  ubuntu2204: "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"
  ubuntu2404: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img"
  rocky9: "https://download.rockylinux.org/pub/rocky/9/images/x86_64/Rocky-9-GenericCloud-Base.latest.x86_64.qcow2"
  alma9: "https://repo.almalinux.org/almalinux/9/cloud/x86_64/images/AlmaLinux-9-GenericCloud-latest.x86_64.qcow2"

# Default cloud-init user per distro
vm_default_users:
  debian12: "debian"
  debian11: "debian"
  ubuntu2204: "ubuntu"
  ubuntu2404: "ubuntu"
  rocky9: "cloud-user"
  alma9: "almalinux"
