---
# Proxmox Cluster Role - Handlers

- name: restart-corosync
  service:
    name: corosync
    state: restarted

- name: restart-pve-cluster
  service:
    name: pve-cluster
    state: restarted

- name: reload-corosync-config
  command: corosync-cfgtool -R
